[package]
name = "otel-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
opentelemetry-prometheus = "0.12.0"
opentelemetry_api = "0.19.0"
opentelemetry_sdk = "0.19.0"
